---
name: Regexp-Log
version: 0.04
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: A base class for log files regexp builders
license: perl
requires:
  Test::More: 0
provides:
  Regexp::Log:
    file: lib/Regexp/Log.pm
    version: 0.04
generated_by: Module::Build version 0.26
